### PR TITLE
CEXIO backfill, balance and incorrect nonce bugfix

### LINKED ISSUE #641: CEXIO getTrades() returned duplicate results
Hello,

I'm trying to use CEX.IO but am met with an error. I've looked around and noticed another exchange was fixed by changing it from 2 hours to 12. Any idea why this error would happen? It seems even after wiping the collection and trying again it still fails at the same spot.

```
fetching pre-roll data:

skipping 10457 hrs of previously collected data

cexio.BTC-USD saved 1000 trades 750 days left
.
error: getTrades() returned duplicate results
{ product_id: 'BTC-USD', from: 376024 }
{ product_id: 'BTC-USD', from: 376024 }
               DATE            PRICE     DIFF            VOL         RSI                         ACTIONS                      BAL                PROFIT
2017-10-17 21:00:00  5621.85 BTC-USD                3
2017-10-17 21:30:00  5587.00 BTC-USD   -0.62%       48
2017-10-17 22:00:00  5580.00 BTC-USD   -0.13%       16
2017-10-17 22:30:00  5589.96 BTC-USD   +0.18%       44
---------------------------- STARTING LIVE TRADING ----------------------------
Press  l  to list available commands.
/home/hype/zenbot/extensions/exchanges/cexio/exchange.js:77
        balance.currency = n(body[opts.currency].available).format('0.00000000')
                                                 ^

TypeError: Cannot read property 'available' of undefined
    at /home/xxx/zenbot/extensions/exchanges/cexio/exchange.js:77:43
    at Request.request [as _callback] (/home/xxx/zenbot/node_modules/cexio-api-node/rest.js:67:16)
    at Request.self.callback (/home/xxx/zenbot/node_modules/cexio-api-node/node_modules/request/request.js:186:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/home/xxx/zenbot/node_modules/cexio-api-node/node_modules/request/request.js:1163:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/home/xxx/zenbot/node_modules/cexio-api-node/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1057:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### PR DESCRIPTION
**Pull request by nedievas**
balance undefined and nonce error crash fix. Should fix #641 issue.

### CODE REVIEW

File: extensions/exchanges/cexio/exchange.js [hunk 1]
```diff
@@ -52,11 +53,14 @@ module.exports = function container (get, set, clear) {
 
     getTrades: function (opts, cb) {
       var func_args = [].slice.call(arguments)
-      var args = opts.from
+      var args = {}
+      if (opts.from) {
+        args = Number(opts.from)
+      }
```
Comment (FunFR) [inline extensions/exchanges/cexio/exchange.js]: backfill does not work anymore with this code

File: extensions/exchanges/cexio/exchange.js [hunk 2]
```diff
@@ -176,15 +179,15 @@ module.exports = function container (get, set, clear) {
       var order = orders['~' + opts.order_id]
       var client = authedClient()
       client.get_order_details(opts.order_id, function (err, body) {
-        if (err || typeof body === 'undefined') return retry('getOrder', func_args, err)
+         if (err || body === 'error: Invalid Order ID') return retry('getOrder', func_args, err)
```
Comment (DeviaVir) [inline extensions/exchanges/cexio/exchange.js]: nit: unexpected whitespace

**Review by DeviaVir — APPROVED** [review]
