### PR TITLE
conf override fixes

### LINKED ISSUE #1304: TypeError: Converting circular structure to JSON
Post Ubuntu updates 2 days ago:

/root/zenbot/node_modules/sosa_mongo/mongo_backend.js:33
      var tmp_obj = JSON.parse(JSON.stringify(obj))
                                    ^
TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at Object.save (/root/zenbot/node_modules/sosa_mongo/mongo_backend.js:33:37)
    at withHooks (/root/zenbot/node_modules/sosa/api.js:68:15)
    at Object.save (/root/zenbot/node_modules/sosa/api.js:65:12)
    at /root/zenbot/commands/trade.js:586:22
    at /root/zenbot/lib/engine.js:220:9
    at /root/zenbot/extensions/exchanges/gdax/exchange.js:281:11
    at Request._callback (/root/zenbot/node_modules/gdax/lib/clients/public.js:64:9)
    at Request.self.callback (/root/zenbot/node_modules/gdax/node_modules/request/request.js:188:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/root/zenbot/node_modules/gdax/node_modules/request/request.js:1171:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/root/zenbot/node_modules/gdax/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

### PR DESCRIPTION
**Pull request by krystophv**
More robust command line input for conf override and prevention of modifying a `require` cached version of the conf by making a clone of it for the app runtime.

Should fix #1304

### CODE REVIEW

File: boot.js [hunk 1]
```diff
@@ -52,19 +54,13 @@ module.exports = function (cb) {
   })
 
   function getConfiguration() {
+    var args = minimist(process.argv.slice(3))
```
Comment (DeviaVir) [inline boot.js]: can we be sure that it is always the third slice?

**Review by DeviaVir — APPROVED** [review]

**Comment by defkev** [comment]
Just for the record.

We are (still) throwing an exception if `conf.js` is missing instead of just erroring-out and falling back to `conf-sample.js`

```
module.js:538
    throw err;
    ^

Error: Cannot find module './conf'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at module.exports (/root/zenbot/boot.js:20:12)
    at Object.<anonymous> (/root/zenbot/zenbot.js:17:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
```

**Comment by evseevnn** [comment]
+1

**Comment by defkev** [comment]
Additionally there now seems to be another problem.

If i parse a conf-override using `--conf` - `conf.js` in `/zenbot` no longer gets parsed because we are now looking for `conf.js` inside the selector directory:

`Error: please configure your ... credentials in /root/zenbot/extensions/exchanges/.../conf.js`

😕

**Comment by krystophv** [comment]
Would you be willing to make a GitHub Issue for it so it doesn't get lost?

**Comment by defkev** [comment]
After looking at boot.js we are now:

1. Parsing `--conf` (inside the selector directory...whyever as this doesn't seem to be related to the commit)
2. Fall back to `conf.js` (die if it doesn't exist)
3. Parse `conf-sample.js`

Wouldn't it make more sense to:

1. Parse `conf.js`
2. Fall back to `conf-sample.js` if it doesn't exist
3. Parse `--conf` if provided and throw an exception and quit if this fails, as i expect the user to actually provide a valid config file if the setting is present after all

This way we 1) load our "main" config (either conf.js or conf-sample.js) 2) Load `--conf` to override whatever is provided by `--conf` of step 1)

**Comment by krystophv** [comment]
Are you running Zenbot from the extension folder? It's currently using `process.cwd()` and it should probably be using `__dirname`. That adjustment can be made at the same time as putting the `conf.js` require attempt in a try/catch.

**Comment by defkev** [comment]
> Are you running Zenbot from the extension folder

From the root folder of zenbot (`/zenbot`), its why i am confused why he is trying to parse it from the selector dir 🤔

**Comment by defkev** [comment]
Ok, i got a PR ready 👆 

Take a look and tell me what you think @krystophv
